name: CI

on:
  push:
  pull_request:
  release:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
        # - {
        #     name: "Windows Latest MSVC",
        #     os: windows-latest,
        #     artifact: "windows_msvc.7z",
        #     build_type: "Release",
        #     cc: "cl",
        #     cxx: "cl",
        #     environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
        #     archiver: "7z a",
        #     generators: "Visual Studio 16 2019"
        #   }
        # - {
        #     name: "Windows Latest MinGW",
        #     os: windows-latest,
        #     artifact: "windows_mingw.7z",
        #     build_type: "Release",
        #     cc: "gcc",
        #     cxx: "g++",
        #     archiver: "7z a",
        #     generators: "Ninja"
        #   }
        - {
            name: "Ubuntu_Latest",
            os: ubuntu-latest,
            artifact: "ubuntu_gcc.7z",
            build_type: "Debug",
            cc: "gcc",
            cxx: "g++",
            archiver: "7z a",
            generators: "Ninja"
          }
        # - {
        #     name: "MacOS_Latest",
        #     os: macos-latest,
        #     artifact: "macos_clang.7z",
        #     build_type: "Debug",
        #     cc: "clang",
        #     cxx: "clang++",
        #     archiver: "7za a",
        #     generators: "Ninja"
        #   }

    steps:
      - uses: actions/checkout@v3

      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}

      - name: Install dependencies on windows
        if: startsWith(matrix.config.os, 'windows')
        run: |
          choco install ninja cmake gcovr doxygen
          ninja --version
          cmake --version

      - name: Install dependencies on ubuntu
        if: startsWith(matrix.config.name, 'Ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build cmake gcovr doxygen ccache
          pip3 install -r ${{github.workspace}}/tools/python/KML/requirements/test_requirements.txt
          pip3 install cython
          ninja --version
          cmake --version
          gcc --version

      - name: Install dependencies on macos
        if: startsWith(matrix.config.os, 'MacOS')
        run: |
          brew install p7zip cmake ninja gcovr doxygen ccache
          pip3 install -r ${{github.workspace}}/tools/python/KML/requirements/test_requirements.txt
          pip3 install cython
          ninja --version
          cmake --version
          clang --version

      - name: Configure CMake
        run: |
          cmake -S . -B ${{github.workspace}}/build \
            -DBUILD_TESTING=ON \
            -DBUILD_PYTHON=ON \
            -DBUILD_COVERAGE=ON \
            -DBUILD_DOCUMENTATION=OFF \
            -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}}

      - name: Build and create artifact
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.config.build_type}} -j

      - name: Compress Uploads
        run: tar -czvf ${{matrix.config.name}}.tar.gz ${{github.workspace}}/build

      - uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.config.name}} artifacts
          path: ${{matrix.config.name}}.tar.gz
          retention-days: 1

  # lint:
  #   name: Lint code
  #   runs-on: ${{matrix.config.os}}
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       config:
  #           - {
  #                name: "Ubuntu_Latest"
  #                os: ubuntu-latest
  #             }
  #   needs: build
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Linter
  #       uses: github/super-linter@v3
  #       env:
  #         DEFAULT_BRANCH: main
  #         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  test:
    name: Test
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: true
      matrix:
        config:
          - {
              name: "Ubuntu_Latest",
              os: ubuntu-latest,
            }
          # - {
          #     name: "MacOS_Latest",
          #     os: macos-latest,
          #   }
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
            name: ${{matrix.config.name}} artifacts
            path: ${{github.workspace}}

      - name: Unpack Artifacts
        run: |
          ls ${{github.workspace}}
          tar -xzvf ${{github.workspace}}/${{matrix.config.name}}.tar.gz -C ${{github.workspace}}

      # - name: Install test dependencies on ubuntu
      #   if: startsWith(matrix.config.name, 'Ubuntu')
      #   run: |
      #     ls ${{github.workspace}}
      #     pip3 install -r ${{github.workspace}}/tools/python/KML/requirements/test_requirements.txt

      # - name: Install test dependencies on macos
      #   if: startsWith(matrix.config.os, 'MacOS')
      #   run: |
      #     pip3 install -r ${{github.workspace}}/tools/python/KML/requirements/test_requirements.txt

      - name: CPP Test
        working-directory: ${{github.workspace}}/build
        run: ctest -V -C ${{matrix.config.build_type}}

      - name: Pytest
        working-directory: ${{github.workspace}}/build
        run: |
          pip3 install ${{github.workspace}}/build/tools/packages/KML*.whl[test]
          cd ${{github.workspace}}/build/tools/python/KML/tests/
          python3 -m pytest -n auto --cov=. --doctest-modules

      - name: CPP Coverage
        working-directory: ${{github.workspace}}/build
        run: make coverage
