---
name: Build and Deploy Docs

# on:
#   workflow_run:
#     workflows: ["CI"]
#     branches: [main]
#     types:
#       - completed

on:
  push:

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    name: Build and Deploy Docs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Requirements
        run: |
          sudo apt-get install doxygen ninja-build cmake ccache
          pip3 install -U cython wheel setuptools>=61.0.0 setuptools_scm
          pip3 install -U sphinx sphinx-rtd-theme sphinx_sitemap breathe \
            exhale sphinx_gallery nbsphinx nbconvert pandoc IPython sphinx_copybutton

      - name: Configure CMake
        run: >-
          cmake
          -DBUILD_TESTING=OFF
          -DBUILD_PYTHON=ON
          -DBUILD_COVERAGE=OFF
          -DBUILD_DOCUMENTATION=ON
          -DBUILD_STATIC_ANALYSIS=OFF
          -DCMAKE_BUILD_TYPE=Release
          -S . -B ${{github.workspace}}/build

      - name: Build Docs
        run: |
          cmake --build ${{github.workspace}}/build --config Release -j
          cd ${{github.workspace}}/build/docs/source/_build/html
          touch .nojekyll

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: cd ${{github.workspace}}/build/docs/source/_build/html
