# Run unit tests using CTest
name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests
      uses: HorstBaerbel/action-ctest@1.1
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build cmake gcovr doxygen
        ninja --version
        cmake --version
        gcc --version
      with:
        sourcedir: '.'
        builddir: 'build'
        cmakeoptions: '--config Release \
			-DCMAKE_INSTALL_PREFIX:PATH=instdir \
            -DBUILD_TESTING=ON \
            -DBUILD_PYTHON=OFF \
            -DBUILD_COVERAGE=OFF \
            -DBUILD_DOCUMENTATION=OFF
		'
        ctestoptions: ''
